// Code generated by "enumer -type=EQAppearanceType"; DO NOT EDIT.

package eqStruct

import (
	"fmt"
)

const (
	_EQAppearanceTypeName_0 = "AT_DieAT_WhoLevelAT_MaxHPAT_InvisAT_PVPAT_Light"
	_EQAppearanceTypeName_1 = "AT_AnimAT_SneakAT_SpawnIDAT_HPAT_LinkDeadAT_LevitateAT_GMAT_AnonAT_GuildIDAT_GuildRankAT_AFKAT_Pet"
	_EQAppearanceTypeName_2 = "AT_SummonedPCAT_SplitAT_SizeAT_NPCAT_NPCName"
	_EQAppearanceTypeName_3 = "AT_DamageState"
	_EQAppearanceTypeName_4 = "AT_Trader"
)

var (
	_EQAppearanceTypeIndex_0 = [...]uint8{0, 6, 17, 25, 33, 39, 47}
	_EQAppearanceTypeIndex_1 = [...]uint8{0, 7, 15, 25, 30, 41, 52, 57, 64, 74, 86, 92, 98}
	_EQAppearanceTypeIndex_2 = [...]uint8{0, 13, 21, 28, 34, 44}
	_EQAppearanceTypeIndex_3 = [...]uint8{0, 14}
	_EQAppearanceTypeIndex_4 = [...]uint8{0, 9}
)

func (i EQAppearanceType) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _EQAppearanceTypeName_0[_EQAppearanceTypeIndex_0[i]:_EQAppearanceTypeIndex_0[i+1]]
	case 14 <= i && i <= 25:
		i -= 14
		return _EQAppearanceTypeName_1[_EQAppearanceTypeIndex_1[i]:_EQAppearanceTypeIndex_1[i+1]]
	case 27 <= i && i <= 31:
		i -= 27
		return _EQAppearanceTypeName_2[_EQAppearanceTypeIndex_2[i]:_EQAppearanceTypeIndex_2[i+1]]
	case i == 44:
		return _EQAppearanceTypeName_3
	case i == 300:
		return _EQAppearanceTypeName_4
	default:
		return fmt.Sprintf("EQAppearanceType(%d)", i)
	}
}

var _EQAppearanceTypeValues = []EQAppearanceType{0, 1, 2, 3, 4, 5, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 44, 300}

var _EQAppearanceTypeNameToValueMap = map[string]EQAppearanceType{
	_EQAppearanceTypeName_0[0:6]:   0,
	_EQAppearanceTypeName_0[6:17]:  1,
	_EQAppearanceTypeName_0[17:25]: 2,
	_EQAppearanceTypeName_0[25:33]: 3,
	_EQAppearanceTypeName_0[33:39]: 4,
	_EQAppearanceTypeName_0[39:47]: 5,
	_EQAppearanceTypeName_1[0:7]:   14,
	_EQAppearanceTypeName_1[7:15]:  15,
	_EQAppearanceTypeName_1[15:25]: 16,
	_EQAppearanceTypeName_1[25:30]: 17,
	_EQAppearanceTypeName_1[30:41]: 18,
	_EQAppearanceTypeName_1[41:52]: 19,
	_EQAppearanceTypeName_1[52:57]: 20,
	_EQAppearanceTypeName_1[57:64]: 21,
	_EQAppearanceTypeName_1[64:74]: 22,
	_EQAppearanceTypeName_1[74:86]: 23,
	_EQAppearanceTypeName_1[86:92]: 24,
	_EQAppearanceTypeName_1[92:98]: 25,
	_EQAppearanceTypeName_2[0:13]:  27,
	_EQAppearanceTypeName_2[13:21]: 28,
	_EQAppearanceTypeName_2[21:28]: 29,
	_EQAppearanceTypeName_2[28:34]: 30,
	_EQAppearanceTypeName_2[34:44]: 31,
	_EQAppearanceTypeName_3[0:14]:  44,
	_EQAppearanceTypeName_4[0:9]:   300,
}

// EQAppearanceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EQAppearanceTypeString(s string) (EQAppearanceType, error) {
	if val, ok := _EQAppearanceTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EQAppearanceType values", s)
}

// EQAppearanceTypeValues returns all values of the enum
func EQAppearanceTypeValues() []EQAppearanceType {
	return _EQAppearanceTypeValues
}

// IsAEQAppearanceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EQAppearanceType) IsAEQAppearanceType() bool {
	for _, v := range _EQAppearanceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
