// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/eqstruct/common.proto

package eqstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StructType int32

const (
	StructType_ST_UNKOWN         StructType = 0
	StructType_ST_PlayerProfile  StructType = 1
	StructType_ST_SpawnPosition  StructType = 2
	StructType_ST_SpawnPositions StructType = 3
)

// Enum value maps for StructType.
var (
	StructType_name = map[int32]string{
		0: "ST_UNKOWN",
		1: "ST_PlayerProfile",
		2: "ST_SpawnPosition",
		3: "ST_SpawnPositions",
	}
	StructType_value = map[string]int32{
		"ST_UNKOWN":         0,
		"ST_PlayerProfile":  1,
		"ST_SpawnPosition":  2,
		"ST_SpawnPositions": 3,
	}
)

func (x StructType) Enum() *StructType {
	p := new(StructType)
	*p = x
	return p
}

func (x StructType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StructType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_eqstruct_common_proto_enumTypes[0].Descriptor()
}

func (StructType) Type() protoreflect.EnumType {
	return &file_proto_eqstruct_common_proto_enumTypes[0]
}

func (x StructType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StructType.Descriptor instead.
func (StructType) EnumDescriptor() ([]byte, []int) {
	return file_proto_eqstruct_common_proto_rawDescGZIP(), []int{0}
}

type DataStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type StructType `protobuf:"varint,1,opt,name=type,proto3,enum=eqstruct.StructType" json:"type,omitempty"`
	Msg  *anypb.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DataStruct) Reset() {
	*x = DataStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStruct) ProtoMessage() {}

func (x *DataStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStruct.ProtoReflect.Descriptor instead.
func (*DataStruct) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_common_proto_rawDescGZIP(), []int{0}
}

func (x *DataStruct) GetType() StructType {
	if x != nil {
		return x.Type
	}
	return StructType_ST_UNKOWN
}

func (x *DataStruct) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlayRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

var File_proto_eqstruct_common_proto protoreflect.FileDescriptor

var file_proto_eqstruct_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65,
	0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x6e, 0x79, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0a,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x71, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x2a, 0x5e, 0x0a, 0x0a, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54, 0x5f,
	0x55, 0x4e, 0x4b, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x5f, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x53, 0x54, 0x5f, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x5f, 0x53, 0x70, 0x61, 0x77, 0x6e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0x03, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x65,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x7a, 0x2f, 0x67, 0x68, 0x6f, 0x65, 0x71, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eqstruct_common_proto_rawDescOnce sync.Once
	file_proto_eqstruct_common_proto_rawDescData = file_proto_eqstruct_common_proto_rawDesc
)

func file_proto_eqstruct_common_proto_rawDescGZIP() []byte {
	file_proto_eqstruct_common_proto_rawDescOnce.Do(func() {
		file_proto_eqstruct_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eqstruct_common_proto_rawDescData)
	})
	return file_proto_eqstruct_common_proto_rawDescData
}

var file_proto_eqstruct_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_eqstruct_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_eqstruct_common_proto_goTypes = []interface{}{
	(StructType)(0),     // 0: eqstruct.StructType
	(*DataStruct)(nil),  // 1: eqstruct.DataStruct
	(*PlayRequest)(nil), // 2: eqstruct.PlayRequest
	(*anypb.Any)(nil),   // 3: google.protobuf.Any
}
var file_proto_eqstruct_common_proto_depIdxs = []int32{
	0, // 0: eqstruct.DataStruct.type:type_name -> eqstruct.StructType
	3, // 1: eqstruct.DataStruct.msg:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_eqstruct_common_proto_init() }
func file_proto_eqstruct_common_proto_init() {
	if File_proto_eqstruct_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eqstruct_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eqstruct_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eqstruct_common_proto_goTypes,
		DependencyIndexes: file_proto_eqstruct_common_proto_depIdxs,
		EnumInfos:         file_proto_eqstruct_common_proto_enumTypes,
		MessageInfos:      file_proto_eqstruct_common_proto_msgTypes,
	}.Build()
	File_proto_eqstruct_common_proto = out.File
	file_proto_eqstruct_common_proto_rawDesc = nil
	file_proto_eqstruct_common_proto_goTypes = nil
	file_proto_eqstruct_common_proto_depIdxs = nil
}
