// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/eqstruct/entity.proto

package eqstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveDoor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoorId int32 `protobuf:"varint,1,opt,name=door_id,json=doorId,proto3" json:"door_id,omitempty"`
	Action int32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *MoveDoor) Reset() {
	*x = MoveDoor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDoor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDoor) ProtoMessage() {}

func (x *MoveDoor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDoor.ProtoReflect.Descriptor instead.
func (*MoveDoor) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{0}
}

func (x *MoveDoor) GetDoorId() int32 {
	if x != nil {
		return x.DoorId
	}
	return 0
}

func (x *MoveDoor) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target        uint32  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Source        uint32  `protobuf:"varint,2,opt,name=source,proto3" json:"source,omitempty"`
	Level         uint32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	InstrumentMod int32   `protobuf:"varint,4,opt,name=instrument_mod,json=instrumentMod,proto3" json:"instrument_mod,omitempty"`
	Force         float32 `protobuf:"fixed32,5,opt,name=force,proto3" json:"force,omitempty"`
	Sequence      float32 `protobuf:"fixed32,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PushupAngle   float32 `protobuf:"fixed32,7,opt,name=pushup_angle,json=pushupAngle,proto3" json:"pushup_angle,omitempty"`
	Type          uint32  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	TapAmount     int32   `protobuf:"varint,9,opt,name=tap_amount,json=tapAmount,proto3" json:"tap_amount,omitempty"`
	Spell         uint32  `protobuf:"varint,10,opt,name=spell,proto3" json:"spell,omitempty"`
	BuffUnknown   uint32  `protobuf:"varint,11,opt,name=buff_unknown,json=buffUnknown,proto3" json:"buff_unknown,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Action) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Action) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Action) GetInstrumentMod() int32 {
	if x != nil {
		return x.InstrumentMod
	}
	return 0
}

func (x *Action) GetForce() float32 {
	if x != nil {
		return x.Force
	}
	return 0
}

func (x *Action) GetSequence() float32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Action) GetPushupAngle() float32 {
	if x != nil {
		return x.PushupAngle
	}
	return 0
}

func (x *Action) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Action) GetTapAmount() int32 {
	if x != nil {
		return x.TapAmount
	}
	return 0
}

func (x *Action) GetSpell() uint32 {
	if x != nil {
		return x.Spell
	}
	return 0
}

func (x *Action) GetBuffUnknown() uint32 {
	if x != nil {
		return x.BuffUnknown
	}
	return 0
}

type BeginCast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CasterId uint32 `protobuf:"varint,1,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	SpellId  uint32 `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	CastTime uint32 `protobuf:"varint,3,opt,name=cast_time,json=castTime,proto3" json:"cast_time,omitempty"`
}

func (x *BeginCast) Reset() {
	*x = BeginCast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginCast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginCast) ProtoMessage() {}

func (x *BeginCast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginCast.ProtoReflect.Descriptor instead.
func (*BeginCast) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{2}
}

func (x *BeginCast) GetCasterId() uint32 {
	if x != nil {
		return x.CasterId
	}
	return 0
}

func (x *BeginCast) GetSpellId() uint32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *BeginCast) GetCastTime() uint32 {
	if x != nil {
		return x.CastTime
	}
	return 0
}

type Damage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target      uint32  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Source      uint32  `protobuf:"varint,2,opt,name=source,proto3" json:"source,omitempty"`
	Type        uint32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	SpellId     uint32  `protobuf:"varint,4,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	Damage      int32   `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
	Force       float32 `protobuf:"fixed32,6,opt,name=force,proto3" json:"force,omitempty"`
	Sequence    float32 `protobuf:"fixed32,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PushupAngle float32 `protobuf:"fixed32,8,opt,name=pushup_angle,json=pushupAngle,proto3" json:"pushup_angle,omitempty"`
}

func (x *Damage) Reset() {
	*x = Damage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{3}
}

func (x *Damage) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Damage) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Damage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Damage) GetSpellId() uint32 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *Damage) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Damage) GetForce() float32 {
	if x != nil {
		return x.Force
	}
	return 0
}

func (x *Damage) GetSequence() float32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Damage) GetPushupAngle() float32 {
	if x != nil {
		return x.PushupAngle
	}
	return 0
}

type HPUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpawnId uint32 `protobuf:"varint,1,opt,name=spawn_id,json=spawnId,proto3" json:"spawn_id,omitempty"`
	HpCur   int32  `protobuf:"varint,2,opt,name=hp_cur,json=hpCur,proto3" json:"hp_cur,omitempty"`
	HpMax   int32  `protobuf:"varint,3,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
}

func (x *HPUpdate) Reset() {
	*x = HPUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HPUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HPUpdate) ProtoMessage() {}

func (x *HPUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HPUpdate.ProtoReflect.Descriptor instead.
func (*HPUpdate) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{4}
}

func (x *HPUpdate) GetSpawnId() uint32 {
	if x != nil {
		return x.SpawnId
	}
	return 0
}

func (x *HPUpdate) GetHpCur() int32 {
	if x != nil {
		return x.HpCur
	}
	return 0
}

func (x *HPUpdate) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

type WearChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpawnId    uint32      `protobuf:"varint,1,opt,name=spawn_id,json=spawnId,proto3" json:"spawn_id,omitempty"`
	WearSlotId uint32      `protobuf:"varint,2,opt,name=wear_slot_id,json=wearSlotId,proto3" json:"wear_slot_id,omitempty"`
	Material   uint32      `protobuf:"varint,3,opt,name=material,proto3" json:"material,omitempty"`
	Color      *TintStruct `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *WearChange) Reset() {
	*x = WearChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WearChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WearChange) ProtoMessage() {}

func (x *WearChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WearChange.ProtoReflect.Descriptor instead.
func (*WearChange) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{5}
}

func (x *WearChange) GetSpawnId() uint32 {
	if x != nil {
		return x.SpawnId
	}
	return 0
}

func (x *WearChange) GetWearSlotId() uint32 {
	if x != nil {
		return x.WearSlotId
	}
	return 0
}

func (x *WearChange) GetMaterial() uint32 {
	if x != nil {
		return x.Material
	}
	return 0
}

func (x *WearChange) GetColor() *TintStruct {
	if x != nil {
		return x.Color
	}
	return nil
}

type TintStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blue  uint32 `protobuf:"varint,1,opt,name=blue,proto3" json:"blue,omitempty"`
	Green uint32 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Red   uint32 `protobuf:"varint,3,opt,name=red,proto3" json:"red,omitempty"`
	Use   uint32 `protobuf:"varint,4,opt,name=use,proto3" json:"use,omitempty"`
}

func (x *TintStruct) Reset() {
	*x = TintStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_entity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TintStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TintStruct) ProtoMessage() {}

func (x *TintStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_entity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TintStruct.ProtoReflect.Descriptor instead.
func (*TintStruct) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_entity_proto_rawDescGZIP(), []int{6}
}

func (x *TintStruct) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *TintStruct) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *TintStruct) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *TintStruct) GetUse() uint32 {
	if x != nil {
		return x.Use
	}
	return 0
}

var File_proto_eqstruct_entity_proto protoreflect.FileDescriptor

var file_proto_eqstruct_entity_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65,
	0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x3b, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x44,
	0x6f, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x6f, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb6, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x75, 0x70, 0x5f, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x75, 0x70, 0x41, 0x6e, 0x67, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x70, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x61, 0x70, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x75,
	0x66, 0x66, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x62, 0x75, 0x66, 0x66, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x60, 0x0a,
	0x09, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xd4, 0x01, 0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x75, 0x70, 0x5f, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x75,
	0x70, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x53, 0x0a, 0x08, 0x48, 0x50, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x68, 0x70, 0x5f, 0x63, 0x75, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68,
	0x70, 0x43, 0x75, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x70, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x70, 0x4d, 0x61, 0x78, 0x22, 0x91, 0x01, 0x0a, 0x0a,
	0x57, 0x65, 0x61, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70,
	0x61, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x70,
	0x61, 0x77, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x77, 0x65, 0x61, 0x72, 0x5f, 0x73, 0x6c,
	0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x77, 0x65, 0x61,
	0x72, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x54, 0x69,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x5a, 0x0a, 0x0a, 0x54, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x65,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x7a, 0x2f, 0x67, 0x68, 0x6f, 0x65, 0x71, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eqstruct_entity_proto_rawDescOnce sync.Once
	file_proto_eqstruct_entity_proto_rawDescData = file_proto_eqstruct_entity_proto_rawDesc
)

func file_proto_eqstruct_entity_proto_rawDescGZIP() []byte {
	file_proto_eqstruct_entity_proto_rawDescOnce.Do(func() {
		file_proto_eqstruct_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eqstruct_entity_proto_rawDescData)
	})
	return file_proto_eqstruct_entity_proto_rawDescData
}

var file_proto_eqstruct_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_eqstruct_entity_proto_goTypes = []interface{}{
	(*MoveDoor)(nil),   // 0: eqstruct.MoveDoor
	(*Action)(nil),     // 1: eqstruct.Action
	(*BeginCast)(nil),  // 2: eqstruct.BeginCast
	(*Damage)(nil),     // 3: eqstruct.Damage
	(*HPUpdate)(nil),   // 4: eqstruct.HPUpdate
	(*WearChange)(nil), // 5: eqstruct.WearChange
	(*TintStruct)(nil), // 6: eqstruct.TintStruct
}
var file_proto_eqstruct_entity_proto_depIdxs = []int32{
	6, // 0: eqstruct.WearChange.color:type_name -> eqstruct.TintStruct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_eqstruct_entity_proto_init() }
func file_proto_eqstruct_entity_proto_init() {
	if File_proto_eqstruct_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eqstruct_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDoor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginCast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Damage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HPUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WearChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_entity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TintStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eqstruct_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eqstruct_entity_proto_goTypes,
		DependencyIndexes: file_proto_eqstruct_entity_proto_depIdxs,
		MessageInfos:      file_proto_eqstruct_entity_proto_msgTypes,
	}.Build()
	File_proto_eqstruct_entity_proto = out.File
	file_proto_eqstruct_entity_proto_rawDesc = nil
	file_proto_eqstruct_entity_proto_goTypes = nil
	file_proto_eqstruct_entity_proto_depIdxs = nil
}
