// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/eqstruct/player.proto

package eqstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checksum      uint32  `protobuf:"varint,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	UniqueGuildId uint32  `protobuf:"varint,2,opt,name=unique_guild_id,json=uniqueGuildId,proto3" json:"unique_guild_id,omitempty"`
	Gender        uint32  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Race          uint32  `protobuf:"varint,4,opt,name=race,proto3" json:"race,omitempty"`
	Class         uint32  `protobuf:"varint,5,opt,name=class,proto3" json:"class,omitempty"`
	BodyType      uint32  `protobuf:"varint,6,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`
	Level         uint32  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint32  `protobuf:"varint,8,opt,name=exp,proto3" json:"exp,omitempty"`
	Points        int32   `protobuf:"varint,9,opt,name=points,proto3" json:"points,omitempty"`
	Mana          int32   `protobuf:"varint,10,opt,name=mana,proto3" json:"mana,omitempty"`
	CurrHp        int32   `protobuf:"varint,11,opt,name=curr_hp,json=currHp,proto3" json:"curr_hp,omitempty"`
	Status        uint32  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Str           uint32  `protobuf:"varint,13,opt,name=str,proto3" json:"str,omitempty"`
	Sta           uint32  `protobuf:"varint,14,opt,name=sta,proto3" json:"sta,omitempty"`
	Cha           uint32  `protobuf:"varint,15,opt,name=cha,proto3" json:"cha,omitempty"`
	Dex           uint32  `protobuf:"varint,16,opt,name=dex,proto3" json:"dex,omitempty"`
	Int           uint32  `protobuf:"varint,17,opt,name=int,proto3" json:"int,omitempty"`
	Agi           uint32  `protobuf:"varint,18,opt,name=agi,proto3" json:"agi,omitempty"`
	Wis           uint32  `protobuf:"varint,19,opt,name=wis,proto3" json:"wis,omitempty"`
	Face          uint32  `protobuf:"varint,20,opt,name=face,proto3" json:"face,omitempty"`
	Position      uint32  `protobuf:"varint,21,opt,name=position,proto3" json:"position,omitempty"`
	ZoneId        uint32  `protobuf:"varint,22,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Hunger        int32   `protobuf:"varint,23,opt,name=hunger,proto3" json:"hunger,omitempty"`
	Thirst        int32   `protobuf:"varint,24,opt,name=thirst,proto3" json:"thirst,omitempty"`
	X             float32 `protobuf:"fixed32,50,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32 `protobuf:"fixed32,51,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32 `protobuf:"fixed32,52,opt,name=z,proto3" json:"z,omitempty"`
	Heading       float32 `protobuf:"fixed32,53,opt,name=heading,proto3" json:"heading,omitempty"`
	Name          string  `protobuf:"bytes,91,opt,name=name,proto3" json:"name,omitempty"`
	LastName      string  `protobuf:"bytes,92,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	LevelChar     string  `protobuf:"bytes,93,opt,name=level_char,json=levelChar,proto3" json:"level_char,omitempty"`
	GenderChar    string  `protobuf:"bytes,94,opt,name=gender_char,json=genderChar,proto3" json:"gender_char,omitempty"`
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerProfile) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *PlayerProfile) GetUniqueGuildId() uint32 {
	if x != nil {
		return x.UniqueGuildId
	}
	return 0
}

func (x *PlayerProfile) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *PlayerProfile) GetRace() uint32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *PlayerProfile) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *PlayerProfile) GetBodyType() uint32 {
	if x != nil {
		return x.BodyType
	}
	return 0
}

func (x *PlayerProfile) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProfile) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerProfile) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *PlayerProfile) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *PlayerProfile) GetCurrHp() int32 {
	if x != nil {
		return x.CurrHp
	}
	return 0
}

func (x *PlayerProfile) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PlayerProfile) GetStr() uint32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *PlayerProfile) GetSta() uint32 {
	if x != nil {
		return x.Sta
	}
	return 0
}

func (x *PlayerProfile) GetCha() uint32 {
	if x != nil {
		return x.Cha
	}
	return 0
}

func (x *PlayerProfile) GetDex() uint32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *PlayerProfile) GetInt() uint32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *PlayerProfile) GetAgi() uint32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

func (x *PlayerProfile) GetWis() uint32 {
	if x != nil {
		return x.Wis
	}
	return 0
}

func (x *PlayerProfile) GetFace() uint32 {
	if x != nil {
		return x.Face
	}
	return 0
}

func (x *PlayerProfile) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlayerProfile) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *PlayerProfile) GetHunger() int32 {
	if x != nil {
		return x.Hunger
	}
	return 0
}

func (x *PlayerProfile) GetThirst() int32 {
	if x != nil {
		return x.Thirst
	}
	return 0
}

func (x *PlayerProfile) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerProfile) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerProfile) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerProfile) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *PlayerProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PlayerProfile) GetLevelChar() string {
	if x != nil {
		return x.LevelChar
	}
	return ""
}

func (x *PlayerProfile) GetGenderChar() string {
	if x != nil {
		return x.GenderChar
	}
	return ""
}

type ExpUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp uint32 `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *ExpUpdate) Reset() {
	*x = ExpUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpUpdate) ProtoMessage() {}

func (x *ExpUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpUpdate.ProtoReflect.Descriptor instead.
func (*ExpUpdate) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{1}
}

func (x *ExpUpdate) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type ManaUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpawnId  uint32 `protobuf:"varint,1,opt,name=spawn_id,json=spawnId,proto3" json:"spawn_id,omitempty"`
	ManaCurr uint32 `protobuf:"varint,2,opt,name=mana_curr,json=manaCurr,proto3" json:"mana_curr,omitempty"`
}

func (x *ManaUpdate) Reset() {
	*x = ManaUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManaUpdate) ProtoMessage() {}

func (x *ManaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManaUpdate.ProtoReflect.Descriptor instead.
func (*ManaUpdate) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{2}
}

func (x *ManaUpdate) GetSpawnId() uint32 {
	if x != nil {
		return x.SpawnId
	}
	return 0
}

func (x *ManaUpdate) GetManaCurr() uint32 {
	if x != nil {
		return x.ManaCurr
	}
	return 0
}

type StaminaUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food    int32 `protobuf:"varint,1,opt,name=food,proto3" json:"food,omitempty"`
	Water   int32 `protobuf:"varint,2,opt,name=water,proto3" json:"water,omitempty"`
	Fatigue int32 `protobuf:"varint,3,opt,name=fatigue,proto3" json:"fatigue,omitempty"`
}

func (x *StaminaUpdate) Reset() {
	*x = StaminaUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaminaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaminaUpdate) ProtoMessage() {}

func (x *StaminaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaminaUpdate.ProtoReflect.Descriptor instead.
func (*StaminaUpdate) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{3}
}

func (x *StaminaUpdate) GetFood() int32 {
	if x != nil {
		return x.Food
	}
	return 0
}

func (x *StaminaUpdate) GetWater() int32 {
	if x != nil {
		return x.Water
	}
	return 0
}

func (x *StaminaUpdate) GetFatigue() int32 {
	if x != nil {
		return x.Fatigue
	}
	return 0
}

type Consider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetId uint32 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Faction  uint32 `protobuf:"varint,3,opt,name=faction,proto3" json:"faction,omitempty"`
	Level    uint32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	CurrHp   int32  `protobuf:"varint,5,opt,name=curr_hp,json=currHp,proto3" json:"curr_hp,omitempty"`
	MaxHp    int32  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Pvpcon   uint32 `protobuf:"varint,7,opt,name=pvpcon,proto3" json:"pvpcon,omitempty"`
}

func (x *Consider) Reset() {
	*x = Consider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consider) ProtoMessage() {}

func (x *Consider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consider.ProtoReflect.Descriptor instead.
func (*Consider) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{4}
}

func (x *Consider) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Consider) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Consider) GetFaction() uint32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *Consider) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Consider) GetCurrHp() int32 {
	if x != nil {
		return x.CurrHp
	}
	return 0
}

func (x *Consider) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Consider) GetPvpcon() uint32 {
	if x != nil {
		return x.Pvpcon
	}
	return 0
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId uint32 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_player_proto_rawDescGZIP(), []int{5}
}

func (x *Target) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

var File_proto_eqstruct_player_proto protoreflect.FileDescriptor

var file_proto_eqstruct_player_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65,
	0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0xe3, 0x05, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x65, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x61, 0x6e, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x61,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x5f, 0x68, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x63, 0x75, 0x72, 0x72, 0x48, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x73, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x73, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x68, 0x61, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x63, 0x68, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x69, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x69, 0x12, 0x10, 0x0a,
	0x03, 0x77, 0x69, 0x73, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x77, 0x69, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x75, 0x6e, 0x67,
	0x65, 0x72, 0x18, 0x17, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x75, 0x6e, 0x67, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x72, 0x73, 0x74, 0x18, 0x18, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x68, 0x69, 0x72, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x32, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x33, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x34, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x7a, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x35, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x5c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x18, 0x5d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x18, 0x5e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x22, 0x1d, 0x0a,
	0x09, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x44, 0x0a, 0x0a,
	0x4d, 0x61, 0x6e, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70,
	0x61, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x70,
	0x61, 0x77, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x5f, 0x63, 0x75,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x43, 0x75,
	0x72, 0x72, 0x22, 0x53, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x61, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x61, 0x74, 0x69, 0x67, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x66, 0x61, 0x74, 0x69, 0x67, 0x75, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x5f, 0x68, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x63, 0x75, 0x72, 0x72, 0x48, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x5f, 0x68,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x76, 0x70, 0x63, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x70, 0x76, 0x70, 0x63, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x6f,
	0x72, 0x65, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x7a, 0x2f, 0x67, 0x68, 0x6f, 0x65, 0x71, 0x2d,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eqstruct_player_proto_rawDescOnce sync.Once
	file_proto_eqstruct_player_proto_rawDescData = file_proto_eqstruct_player_proto_rawDesc
)

func file_proto_eqstruct_player_proto_rawDescGZIP() []byte {
	file_proto_eqstruct_player_proto_rawDescOnce.Do(func() {
		file_proto_eqstruct_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eqstruct_player_proto_rawDescData)
	})
	return file_proto_eqstruct_player_proto_rawDescData
}

var file_proto_eqstruct_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_eqstruct_player_proto_goTypes = []interface{}{
	(*PlayerProfile)(nil), // 0: eqstruct.PlayerProfile
	(*ExpUpdate)(nil),     // 1: eqstruct.ExpUpdate
	(*ManaUpdate)(nil),    // 2: eqstruct.ManaUpdate
	(*StaminaUpdate)(nil), // 3: eqstruct.StaminaUpdate
	(*Consider)(nil),      // 4: eqstruct.Consider
	(*Target)(nil),        // 5: eqstruct.Target
}
var file_proto_eqstruct_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_eqstruct_player_proto_init() }
func file_proto_eqstruct_player_proto_init() {
	if File_proto_eqstruct_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eqstruct_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManaUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaminaUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eqstruct_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eqstruct_player_proto_goTypes,
		DependencyIndexes: file_proto_eqstruct_player_proto_depIdxs,
		MessageInfos:      file_proto_eqstruct_player_proto_msgTypes,
	}.Build()
	File_proto_eqstruct_player_proto = out.File
	file_proto_eqstruct_player_proto_rawDesc = nil
	file_proto_eqstruct_player_proto_goTypes = nil
	file_proto_eqstruct_player_proto_depIdxs = nil
}
