// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/eqstruct/raid.proto

package eqstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaidGeneral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     uint32 `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	LeaderName string `protobuf:"bytes,3,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	Parameter  uint32 `protobuf:"varint,4,opt,name=parameter,proto3" json:"parameter,omitempty"`
}

func (x *RaidGeneral) Reset() {
	*x = RaidGeneral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_raid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaidGeneral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidGeneral) ProtoMessage() {}

func (x *RaidGeneral) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_raid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidGeneral.ProtoReflect.Descriptor instead.
func (*RaidGeneral) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_raid_proto_rawDescGZIP(), []int{0}
}

func (x *RaidGeneral) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *RaidGeneral) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *RaidGeneral) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *RaidGeneral) GetParameter() uint32 {
	if x != nil {
		return x.Parameter
	}
	return 0
}

type RaidAddMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RaidGeneral     *RaidGeneral `protobuf:"bytes,1,opt,name=raid_general,json=raidGeneral,proto3" json:"raid_general,omitempty"`
	Class           uint32       `protobuf:"varint,2,opt,name=class,proto3" json:"class,omitempty"`
	Level           uint32       `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	GroupLeaderFlag uint32       `protobuf:"varint,4,opt,name=group_leader_flag,json=groupLeaderFlag,proto3" json:"group_leader_flag,omitempty"` //flags here if needed
}

func (x *RaidAddMember) Reset() {
	*x = RaidAddMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_raid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaidAddMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidAddMember) ProtoMessage() {}

func (x *RaidAddMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_raid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidAddMember.ProtoReflect.Descriptor instead.
func (*RaidAddMember) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_raid_proto_rawDescGZIP(), []int{1}
}

func (x *RaidAddMember) GetRaidGeneral() *RaidGeneral {
	if x != nil {
		return x.RaidGeneral
	}
	return nil
}

func (x *RaidAddMember) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *RaidAddMember) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RaidAddMember) GetGroupLeaderFlag() uint32 {
	if x != nil {
		return x.GroupLeaderFlag
	}
	return 0
}

type RaidCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     uint32 `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	LeaderName string `protobuf:"bytes,2,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderId   uint32 `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
}

func (x *RaidCreate) Reset() {
	*x = RaidCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eqstruct_raid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaidCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidCreate) ProtoMessage() {}

func (x *RaidCreate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqstruct_raid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidCreate.ProtoReflect.Descriptor instead.
func (*RaidCreate) Descriptor() ([]byte, []int) {
	return file_proto_eqstruct_raid_proto_rawDescGZIP(), []int{2}
}

func (x *RaidCreate) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *RaidCreate) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *RaidCreate) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

var File_proto_eqstruct_raid_proto protoreflect.FileDescriptor

var file_proto_eqstruct_raid_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2f, 0x72, 0x61, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x71, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x52, 0x61, 0x69, 0x64, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x22, 0xa1, 0x01,
	0x0a, 0x0d, 0x52, 0x61, 0x69, 0x64, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x38, 0x0a, 0x0c, 0x72, 0x61, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x52, 0x61, 0x69, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x0b, 0x72, 0x61,
	0x69, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x46, 0x6c, 0x61,
	0x67, 0x22, 0x62, 0x0a, 0x0a, 0x52, 0x61, 0x69, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x6f, 0x72, 0x65, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x7a, 0x2f, 0x67, 0x68, 0x6f, 0x65, 0x71, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eqstruct_raid_proto_rawDescOnce sync.Once
	file_proto_eqstruct_raid_proto_rawDescData = file_proto_eqstruct_raid_proto_rawDesc
)

func file_proto_eqstruct_raid_proto_rawDescGZIP() []byte {
	file_proto_eqstruct_raid_proto_rawDescOnce.Do(func() {
		file_proto_eqstruct_raid_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eqstruct_raid_proto_rawDescData)
	})
	return file_proto_eqstruct_raid_proto_rawDescData
}

var file_proto_eqstruct_raid_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_eqstruct_raid_proto_goTypes = []interface{}{
	(*RaidGeneral)(nil),   // 0: eqstruct.RaidGeneral
	(*RaidAddMember)(nil), // 1: eqstruct.RaidAddMember
	(*RaidCreate)(nil),    // 2: eqstruct.RaidCreate
}
var file_proto_eqstruct_raid_proto_depIdxs = []int32{
	0, // 0: eqstruct.RaidAddMember.raid_general:type_name -> eqstruct.RaidGeneral
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_eqstruct_raid_proto_init() }
func file_proto_eqstruct_raid_proto_init() {
	if File_proto_eqstruct_raid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eqstruct_raid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaidGeneral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_raid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaidAddMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eqstruct_raid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaidCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eqstruct_raid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eqstruct_raid_proto_goTypes,
		DependencyIndexes: file_proto_eqstruct_raid_proto_depIdxs,
		MessageInfos:      file_proto_eqstruct_raid_proto_msgTypes,
	}.Build()
	File_proto_eqstruct_raid_proto = out.File
	file_proto_eqstruct_raid_proto_rawDesc = nil
	file_proto_eqstruct_raid_proto_goTypes = nil
	file_proto_eqstruct_raid_proto_depIdxs = nil
}
